### ISSUE TITLE
Missing Icon File (Source path does not exist: resources/android/icon/drawable-hdpi-icon.png)

### ISSUE THREAD

**Issue by FranckEtiam** [codesundar/ionic-uber-clone#16]
I can not run the application on a virtual device.......

Android Studio project detected

(node:7840) UnhandledPromiseRejectionWarning: Error: Source path does not exist: resources/android/icon/drawable-hdpi-icon.png
    at updatePathInternal (G:\Dony\rider\platforms\android\cordova\node_modules\cordova-common\src\FileUpdater.js:145:19)
    at G:\Dony\rider\platforms\android\cordova\node_modules\cordova-common\src\FileUpdater.js:223:19
    at Array.forEach (<anonymous>)
    at Object.updatePaths (G:\Dony\rider\platforms\android\cordova\node_modules\cordova-common\src\FileUpdater.js:221:33)
    at updateIcons (G:\Dony\rider\platforms\android\cordova\lib\prepare.js:388:17)
    at G:\Dony\rider\platforms\android\cordova\lib\prepare.js:49:9
    at _fulfilled (G:\Dony\rider\platforms\android\cordova\node_modules\q\q.js:854:54)
    at self.promiseDispatch.done (G:\Dony\rider\platforms\android\cordova\node_modules\q\q.js:883:30)
    at Promise.promise.promiseDispatch (G:\Dony\rider\platforms\android\cordova\node_modules\q\q.js:816:13)
    at G:\Dony\rider\platforms\android\cordova\node_modules\q\q.js:624:44
(node:7840) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7840) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

[OK] Your app has been deployed.
     Did you know you can live-reload changes from your app with --livereload?

**Comment by codesundar** [comment]
**Error**: Source path does not exist: resources/android/icon/drawable-hdpi-icon.png

It seems like, It couldn't create an icon for your project

**Solutions:**
- Create any new ionic project
- Change your directory
- Run `ionic cordova resources`
- It will create folder called resources
- Now, Copy your resources folder & paste it on rider, driver and admin 's root folder
- Run app
