### ISSUE TITLE
Runtime Error when rquesting ride.

### ISSUE THREAD

**Issue by TheErondu** [codesundar/ionic-uber-clone#17]
*I'm on browser and haven't built for android 
got this error while trying to request driver.
when i click the RIDE NOW BUTTON
`Error: Firebase.set failed: First argument contains undefined in property 'deals.lPGnTjTymSh2gdNDVz1WHoFgw7K2.fee'
    at Pd (http://localhost:8100/build/vendor.js:44901:67)
    at http://localhost:8100/build/vendor.js:44902:166
    at fb (http://localhost:8100/build/vendor.js:44847:691)
    at Pd (http://localhost:8100/build/vendor.js:44901:424)
    at Od (http://localhost:8100/build/vendor.js:44900:694)
    at U.g.set (http://localhost:8100/build/vendor.js:45053:241)
    at FirebaseObjectObservable.set (http://localhost:8100/build/vendor.js:91135:26)
    at DealService.webpackJsonp.297.DealService.makeDeal (http://localhost:8100/build/main.js:911:52)
    at SafeSubscriber._next (http://localhost:8100/build/main.js:1493:39)
    at SafeSubscriber.__tryOrUnsub (http://localhost:8100/build/vendor.js:22552:16)`

**Comment by codesundar** [comment]
Thanks for reporting!

Why is this error happening?
- Car fee is not getting (or) not calculating after choosing a location

**Solution:**
- If you might not add google billing, you're limited to API access. so calculation might not work. (Please check with your google billing)
- You might not add a fee for the car. please check your admin panel for car fee

**Comment by TheErondu** [comment]
> Thanks for reporting!
> 
> Why is this error happening?
> 
> * Car fee is not getting (or) not calculating after choosing a location
> 
> **Solution:**
> 
> * If you might not add google billing, you're limited to API access. so calculation might not work. (Please check with your google billing)
> * You might not add a fee for the car. please check your admin panel for car fee

Checked my google cloud and billing was not enabled... strange as i had enabled it before..
I also Updated the Prices increased from 0.2 to 100 per km.
it worked now! thanks. Closing Issue as solved..
